id: gh_actions_download_yml
hints:
  - The 'ci_testing.yml' should be placed in the '.github/workflows/' directory.
  - The 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: Hey there, we are planning to deploy a new feature and we want to automate all of the necessary tests we need to run for this feature. We should be able to do this with Github Actions. 
        delay: 2000
      - text: :instruction[Here are [the tests] we need to run, and this is [the YAML file]() you’ll need to build the workflow. Please push these files to the repo and open a PR.]{block=true} 
        delay: 3500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
        key: "${eventType}"
        cases:
          github_pr_opened:
            do:
              - actionId: bot_message
                params:
                  person: keen
                  messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: On it, I'll review the changes right away.
            if:
              conditions:
              - conditionId: github_is_file_added
                params:
                  fileName: .github/workflows/ci_testing.yml
                onFalseParams:
                  pr_reject_message: "Make sure you add the ci_testing.yml file in the right path"
                  pr_reject_message_name: "ci_yml_missing"
              - conditionId: github_is_file_added
                params:
                  fileName: src/tests/ci.test.js
                onFalseParams:
                  pr_reject_message: "Make sure you add the ci.test.js file in the right path"
                  pr_reject_message_name: "ci_tests_missing"
              then:
                do:
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: Looking good! You can merge the PR now.
          github_pr_merged:
            do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                - text: Nice job!
                  delay: 1000
            - actionId: finish_step
