id: gh_actions_download_yml
hints:
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Let's create a new CI flow to run our tests on each PR"
        delay: 2000
      - text: "Download [this yml file](), and [this test file](), then add it to a new branch, push to GH and open a PR."
        delay: 3500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
        key: "${eventType}"
        cases:
          github_pr_opened:
            do:
              - actionId: bot_message
                params:
                  person: keen
                  messages:
                  - text: "On it, I'll review the changes right away."
                    delay: 1000
              - actionId: github_pr_comment
                params:
                  person: keen
                  message: "On it, I'll review the changes right away."
          github_pr_workflow_complete_success:
            if:
              conditions:
                - conditionId: github_is_file_added
                  params:
                    fileName: .github/workflows/ci_testing.yml
                - conditionId: github_is_file_added
                  params:
                    fileName: src/tests/ci.test.js
              then:
                do:
                - actionId: github_pr_approve
                  params:
                    person: keen
                    message: "Looking good! You can merge the PR now."
            else:
              - actionId: github_pr_reject
                params:
                  person: keen
                  message: "Make sure you added the correct files in the correct paths"
          github_pr_merged:
            do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                - text: "Nice job!"
                  delay: 1000
            - actionId: finish_step
