id: gh_actions_troubleshooting
learningObjectives: 
-  Troubleshooting Test Failures 
hints:
- Once pushed to the repository, the workflow YAML should run the tests immediately when a new PR is opened. Try checking if there is a problem with the file. 
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: It looks like the files were added but the Github Actions in the workflow didn't run. I think we have everything we need. Please check what the problem is and fix it. Open a new PR when you're done. 
        delay: 1500
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: "${eventType}"
      cases:
        github_pr_opened:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: Got it. Checking the changes now.
                delay: 1000
          - actionId: github_pr_comment
            params:
              person: keen
              message: Got it. Checking the changes now.
        github_pr_workflow_complete_success:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: Nice work, @${user.githubuser}! You can now merge the PR.
                delay: 2000
          - actionId: github_pr_approve
            params:
              person: keen
              message: Nice work, @${user.githubuser}! You can now merge the PR.
        github_pr_workflow_complete_failure:
          do:
          - actionId: bot_message
            params:
              person: keen
              messages:
              - text: Looks like this code change didn’t fix the problem. Can you take a second look?
                delay: 3000
          - actionId: github_pr_reject
            params:
              person: keen
              message: Looks like this code change didn’t fix the problem. Can you take a second look?
        github_pr_merged:
          do:
          - actionId: finish_step
